### ISSUE TITLE
Nozzle Changer

### ISSUE THREAD

**Issue by AzureOz** [PixiePlacer/PixiePlacer#1]
Great project, thank you for sharing it.  I know you are just starting to post info on various parts of the project and I look forward to your updates.
Are you able to add any info on the Juki Nozzle Changer?
Any setup, connection, configuration and programming needed for the changer operation and it's servo drive.
A video of it changing bits would be wonderful.

**Comment by slaesh** [comment]
great stuff. recently saw this [video here](https://www.youtube.com/watch?v=kQ9cqHOH0Uc) from @Mike-Menci. looks similar, maybe you guys can connect and build one awesome instead of two great ones :)

**Comment by Mike-Menci** [comment]
Salaesh - Similar to ??

**Comment by Mike-Menci** [comment]
Oh I see what you mean...

**Comment by PixiePlacer** [comment]
Yes the design is based on the work of @Mike-Menci. Credits are now given [here](https://github.com/PixiePlacer/PixiePlacer/wiki/Nozzle-Changing-Station). I would love to colaborate on the desin. Mike does amazing work, especially his work on the Component Feeders.

**Comment by PixiePlacer** [comment]
I am using this head: [Link](https://www.aliexpress.us/item/3256801583850616.html?aff_fcid=c96404d5d496401aa4257c78efc0dff6-1701633164343-06909-_DeD1psH&tt=CPS_NORMAL&aff_fsk=_DeD1psH&aff_platform=portals-tool&sk=_DeD1psH&aff_trace_key=c96404d5d496401aa4257c78efc0dff6-1701633164343-06909-_DeD1psH&terminal_id=c38732c4f6c34e588ce9d3f81f8d192c&afSmartRedirect=y&gatewayAdapt=glo2usa4itemAdapt)

**Comment by PixiePlacer** [comment]
@Mike-Menci I love your feeder designs a lot and I can't wait to see your progress in the future. DM me on Discord if you want ;)
