### ISSUE TITLE
can one contribute?

### ISSUE THREAD

**Issue by Contomo** [PixiePlacer/PixiePlacer#10]
Sorry im kinda new to github so im not sure issues is the right place but, i built the pixiplacer using 15mm rails instead of the 12mm ones, i redesigned some parts and designed fitting optical endstops, a mount for the BTT octopus V1 pro a cable chain with adapters etc etc
is there a place to post/share those?

**Comment by PixiePlacer** [comment]
Hello @Contomo,
thats amazing that you have build the machine. I would love to see some pictures of the machine if possible.
Sure I can upload the files if you want. Just send me an Email to: PixiePlacer@outlook.com or DM on Discord.
PixiePlacer
