### ISSUE TITLE
solder paste dispenser

### ISSUE THREAD

**Issue by AndreyFly007** [PixiePlacer/PixiePlacer#11]
Спасибо, что поделились проектом. 
На какой стадии дозатор паяльной пасты? Проект будет продолжаться?

Thanks for sharing the project.
At what stage is the solder paste dispenser? Will the project continue?

**Comment by PixiePlacer** [comment]
Hey,
I am currently not working on the solder paste dispenser. I woudn't bet on me continuing the development of the solder paste dispenser
