### ISSUE TITLE
Clarify the Vaccuum sensor part number. 

### ISSUE THREAD

**Issue by edcasati** [PixiePlacer/PixiePlacer#2]
I am having trouble locating the Vaccuum sensor.
The P/N that you provide is "NC3RR-96FJ4-KP6JP-MGM8W-VH66Y" but can't be found.

**Comment by PixiePlacer** [comment]
Sorry, the part number is: ZSE30A-01-N-L
Glad I could help you :)

Am 06.10.2023 um 17:28 schrieb Edward Casati ***@***.***>:

﻿

I am having trouble locating the Vaccuum sensor.
The P/N that you provide is "NC3RR-96FJ4-KP6JP-MGM8W-VH66Y" but can't be found.
