### ISSUE TITLE
Wiring detail regarding relays and stepping down voltage.

### ISSUE THREAD

**Issue by Jai-R1gby** [PixiePlacer/PixiePlacer#7]
Hi there,

Was wondering if it would be possible to get some greater detail regarding the wiring setup of the relays and how they connect to the main board. Once they are connected to the main board how is this then addressed by Marlin. 

Many thanks.

**Comment by PixiePlacer** [comment]
Hey,
see this [link ](https://github.com/PixiePlacer/PixiePlacer/wiki/Marlin-%E2%80%90-Motion-Controller)for the detailed wiring.
